name: Generate Docker image

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate tags
      id: tags
      run: |
        DOCKER_IMAGE=xboxdev/nxdk-buildbase
        TAGS="${DOCKER_IMAGE}:latest"
        TAGS="$TAGS,${DOCKER_IMAGE}:git-${GITHUB_SHA::8}"
        TAGS="$TAGS,ghcr.io/${DOCKER_IMAGE}:latest"
        TAGS="$TAGS,ghcr.io/${DOCKER_IMAGE}:git-${GITHUB_SHA::8}"
        echo ::set-output name=tags::${TAGS}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/386
        push: true
        tags: ${{ steps.tags.outputs.tags }}
