name: Generate Docker image

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Generate tags (buildbase)
      id: tags-buildbase
      run: |
        DOCKER_IMAGE=xboxdev/nxdk-buildbase
        TAGS="ghcr.io/${DOCKER_IMAGE}:latest"
        TAGS="$TAGS,ghcr.io/${DOCKER_IMAGE}:git-${GITHUB_SHA::8}"
        echo ::set-output name=tags::${TAGS}
    - name: Generate tags (runbase)
      id: tags-runbase
      run: |
        DOCKER_IMAGE=xboxdev/nxdk-runbase
        TAGS="ghcr.io/${DOCKER_IMAGE}:latest"
        TAGS="$TAGS,ghcr.io/${DOCKER_IMAGE}:git-${GITHUB_SHA::8}"
        echo ::set-output name=tags::${TAGS}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push (buildbase)
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/386
        push: true
        target: buildbase
        tags: ${{ steps.tags-buildbase.outputs.tags }}
    - name: Build and push (runbase)
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/386
        push: true
        target: runbase
        tags: ${{ steps.tags-runbase.outputs.tags }}
